Repository tqtezos/minter, pull requests merged in 2021-04, with the labels that each got.

#306 Responsive New Asset Flow
  src/components/CreateNonFungiblePage/CollectionSelect.tsx
  src/components/CreateNonFungiblePage/Confirmation.tsx
  src/components/CreateNonFungiblePage/FileUpload.tsx
  src/components/CreateNonFungiblePage/Form.tsx
  src/components/CreateNonFungiblePage/index.tsx
  src/reducer/slices/createNft.ts
  src/reducer/validators/createNft.ts
Labels: branch:feature

#319 feat: Add error handling to marketplace action modals
  src/components/Collections/Catalog/Sidebar.tsx
  src/components/Collections/TokenDetail/index.tsx
  src/components/CreateNonFungiblePage/CollectionSelect.tsx
  src/components/common/BuyToken.tsx
  src/components/common/SellToken.tsx
  src/components/common/modals/BuyToken.tsx
  src/components/common/modals/CancelTokenSale.tsx
  src/components/common/modals/CreateCollection.tsx
  src/components/common/modals/SellToken.tsx
  src/components/common/modals/TransferToken.tsx
Labels: branch:feature

#338 [Hotfix: Mrkt] -- "faster" load
  src/components/App/index.tsx
Labels: enhancement

#336 [Layout:Style] -- Fullscreen
  src/components/Collections/TokenDetail/index.tsx
  src/components/common/modals/SellToken.tsx
Labels: enhancement

#358 [Issue] -- #349
  src/reducer/async/queries.ts
Labels: bug

#364 UI Changes - #356, #363
  src/components/Collections/Catalog/CollectionDisplay.tsx
  src/components/Collections/Catalog/CollectionsDropdown.tsx
  src/components/CreateNonFungiblePage/CollectionSelect.tsx
Labels: enhancement

#368 Integrate Google model-viewer for GLB/GLTF support
  public/index.html
  src/@types/jsx-intrinsic.d.ts
  src/components/Collections/Catalog/CollectionDisplay.tsx
  src/components/Collections/TokenDetail/index.tsx
  src/components/CreateNonFungiblePage/FileUpload.tsx
  src/components/Marketplace/Catalog/FeaturedToken.tsx
  src/components/Marketplace/Catalog/TokenCard.tsx
  src/components/common/TokenMedia.tsx
  src/index.css
  src/reducer/async/actions.ts
Labels: enhancement

#371 Infinite Scrolling for Marketplace
  config/mainnet.json
  config/sandbox.json
  config/testnet.json
  src/components/Collections/Catalog/CollectionDisplay.tsx
  src/components/Collections/TokenDetail/index.tsx
  src/components/Marketplace/Catalog/FeaturedToken.tsx
  src/components/Marketplace/Catalog/TokenCard.tsx
  src/components/Marketplace/Catalog/index.tsx
  src/components/common/TokenMedia.tsx
  src/components/common/VisibilityTrigger.tsx
  src/lib/nfts/queries.ts
  src/lib/service/tzkt.ts
  src/lib/system.ts
  src/lib/util/ipfs.ts
  src/reducer/async/queries.ts
  src/reducer/slices/marketplace.ts
Labels: enhancement

#383 Fix failing tzkt call
  src/lib/nfts/queries.ts
Labels: branch:hotfix

#389 custom configuration wizard
  README.md
  package.json
  scripts/bootstrap-contracts-config.ts
  scripts/bootstrap.ts
  scripts/tsconfig.json
  src/lib/nfts/queries.ts
  yarn.lock
Labels: documentation, enhancement
