Repository tqtezos/minter, pull requests merged in 2021-03, with the labels that each got.

#208 Added placeholder Pinata API keys.
  config/minter.mainnet.example.json
Labels: branch:hotfix

#225 FIX Image Upload Preview Size
  client/src/components/CreateNonFungiblePage/FileUpload.tsx
  client/src/components/CreateNonFungiblePage/Preview.tsx
Labels: branch:hotfix

#222 Reset Wallet Selection on Permission Failure
  client/src/lib/system.ts
Labels: branch:hotfix

#233 v0.3.0
  README.md
  client/package.json
  client/src/components/Collections/Catalog/TokenGrid.tsx
  client/src/components/Collections/TokenDetail/index.tsx
  client/src/components/CreateNonFungiblePage/FileUpload.tsx
  client/src/components/CreateNonFungiblePage/Preview.tsx
  client/src/components/CreateNonFungiblePage/StatusModal.tsx
  client/src/components/CreateNonFungiblePage/index.tsx
  client/src/components/common/BuyToken.tsx
  client/src/components/common/CreateCollection.tsx
  client/src/components/common/SellToken.tsx
  client/src/components/common/TransferToken.tsx
  client/src/components/common/index.tsx
  client/src/index.tsx
  client/src/lib/nfts/actions.ts
  client/src/lib/nfts/queries.ts
  client/src/lib/system.ts
  client/src/reducer/async/actions.ts
  client/src/reducer/async/errors.ts
  client/src/reducer/slices/notifications.ts
  client/src/reducer/slices/status.ts
  client/yarn.lock
  package.json
  scripts/bootstrap-contracts-config.ts
  yarn.lock
Labels: branch:release

#230 added contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: admin

#250 changed shields to reflect version
  README.md
Labels: branch:hotfix

#254 Support any FA2 with required entrypoints.
  src/lib/nfts/queries.ts
Labels: branch:feature

#262 Get Rid of Preview Text on Asset Creation
  src/components/CreateNonFungiblePage/Preview.tsx
Labels: branch:feature

#264 Carbon savings message on creation of NFT
  src/components/CreateNonFungiblePage/StatusModal.tsx
Labels: branch:feature

#251 Add video metadata types to file upload page.
  src/components/CreateNonFungiblePage/FileUpload.tsx
Labels: branch:feature

#276 feat: Update fa2_tzip16_compat_multi_nft_asset.ts
  scripts/bootstrap-contracts-config.ts
  src/lib/nfts/code/fa2_tzip16_compat_multi_nft_asset.ts
Labels: branch:feature

#278 v0.4.3
  README.md
  scripts/bootstrap-contracts-config.ts
  src/components/CreateNonFungiblePage/FileUpload.tsx
  src/components/CreateNonFungiblePage/Preview.tsx
  src/components/CreateNonFungiblePage/StatusModal.tsx
  src/lib/nfts/code/fa2_tzip16_compat_multi_nft_asset.ts
Labels: branch:release

#248 Add badge to display network when not on mainnet.
  src/components/common/Header.tsx
Labels: branch:feature

#252 Link contract to explorer GUI.
  src/components/Collections/Catalog/index.tsx
Labels: branch:feature

#249 Responsive UI
  src/components/Collections/Catalog/TokenGrid.tsx
Labels: branch:feature, enhancement, ui

#280 Initial marketplace UI implementation
  docker-compose.yml
  package.json
  scripts/bootstrap-contracts-config.ts
  src/components/App/index.tsx
  src/components/Collections/Catalog/index.tsx
  src/components/Marketplace/Catalog/FeaturedToken.tsx
  src/components/Marketplace/Catalog/TokenCard.tsx
  src/components/Marketplace/Catalog/index.tsx
  src/components/SplashPage/index.tsx
  src/components/common/Header.tsx
  src/components/common/TokenMedia.tsx
  src/components/common/assets/splash-logo.svg
  src/lib/nfts/actions.ts
  src/lib/nfts/queries.ts
  src/lib/service/bcd.ts
  src/lib/system.ts
  src/reducer/async/actions.ts
  src/reducer/async/errors.ts
  src/reducer/async/queries.ts
  src/reducer/index.ts
  src/reducer/slices/collections.ts
  src/reducer/slices/marketplace.ts
  yarn.lock
Labels: branch:feature, ui

#260 Reskin of the asset detail page and Ntf metadata typing
  docs/20200716_InitialOutline.md
  scripts/bootstrap-contracts-config.ts
  src/components/Collections/TokenDetail/index.tsx
  src/components/CreateNonFungiblePage/Form.tsx
  src/index.css
  src/index.tsx
  src/lib/nfts/actions.ts
  src/lib/nfts/queries.ts
  src/reducer/async/actions.ts
  src/reducer/slices/createNft.ts
Labels: ui
